tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef
credentials-file: /root/.cloudflared/6ff42ae2-765d-4adf-8112-31c55c1551ef.json

ingress:
  - hostname: gitlab.example.com
    service: http://localhost:8090
  - hostname: registry.example.com
    service: ssh://localhost:22
  - service: http_status:404
