version: "3.7"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.fengzhao.work'
    environment:
      # 容器用东八时区
      TZ: Asia/Shanghai
      GITLAB_OMNIBUS_CONFIG: | 
      # gitlab对外的域名，容器内用80端口
        external_url 'http://gitlab.example.com'
      # gitlab-registry对外的域名，容器内用80端口
        registry_external_url "http://registry.example.com"
      # gitlab用东八时区  
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        
      # 邮件通知相关配置  
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.163.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "your_mail_address@163.com"
        gitlab_rails['smtp_password'] = "authorization code"
        gitlab_rails['smtp_domain'] = "163.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        # 修改gitlab配置的发信人
        gitlab_rails['gitlab_email_from'] = "your_mail_address@163.com"
        user["git_user_email"] = "your_mail_address@163.com"
    ports:
      # 宿主机端口:容器端口
      - '8484:80'
      - '8585:443'
      - '2323:22'
        
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - '/volume1/scripts/docker/gitlab/gitlab-runner:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab:
